# Generated by Django 5.2 on 2025-05-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stampapplication',
            name='payment_receipt',
        ),
    ]
