# Generated by Django 5.2 on 2025-05-07 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_stampapplication_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsetting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adminsetting',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='adminsetting',
            name='key',
        ),
        migrations.RemoveField(
            model_name='adminsetting',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='setting_type',
            field=models.CharField(choices=[('background_image', 'Background Image'), ('logo', 'Logo'), ('primary_color', 'Primary Color'), ('secondary_color', 'Secondary Color'), ('custom_css', 'Custom CSS'), ('custom_js', 'Custom JavaScript')], default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
