# Generated by Django 5.2 on 2025-05-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_adminsetting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampapplication',
            name='advocate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_applications', to='core.advocate'),
        ),
    ]
