# Generated by Django 5.2 on 2025-05-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_stampapplication_advocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
