# Generated by Django 5.2 on 2025-04-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Ink Order', 'verbose_name_plural': 'Ink Orders'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='created',
        ),
    ]
