# Generated by Django 5.2 on 2025-05-09 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_supportticket_status_alter_supportticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='setting_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='setting_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
